services:
  postgres:
    image: ankane/pgvector
    container_name: makima-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
